version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Asmita
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: